# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'UserProfile'
        db.create_table(u'userspace_userprofile', (
            ('user', self.gf('annoying.fields.AutoOneToOneField')(related_name='profile', unique=True, primary_key=True, to=orm['auth.User'])),
            ('lang', self.gf('django.db.models.fields.CharField')(default='en', max_length=10)),
            ('description', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('rank_pts', self.gf('django.db.models.fields.IntegerField')(default=0, blank=True)),
            ('gender', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('gplus_url', self.gf('django.db.models.fields.URLField')(max_length=255, null=True, blank=True)),
            ('fb_url', self.gf('django.db.models.fields.URLField')(max_length=255, null=True, blank=True)),
            ('avatar', self.gf('django.db.models.fields.files.ImageField')(default='img/avatars/anonymous.png', max_length=100)),
            ('thumbnail', self.gf('django.db.models.fields.files.ImageField')(default='img/avatars/30x30_anonymous.png', max_length=100)),
            ('background_image', self.gf('django.db.models.fields.files.ImageField')(default='img/backgrounds/background.jpg', max_length=100)),
        ))
        db.send_create_signal(u'userspace', ['UserProfile'])

        # Adding M2M table for field mod_areas on 'UserProfile'
        m2m_table_name = db.shorten_name(u'userspace_userprofile_mod_areas')
        db.create_table(m2m_table_name, (
            ('id', models.AutoField(verbose_name='ID', primary_key=True, auto_created=True)),
            ('userprofile', models.ForeignKey(orm[u'userspace.userprofile'], null=False)),
            ('location', models.ForeignKey(orm[u'locations.location'], null=False))
        ))
        db.create_unique(m2m_table_name, ['userprofile_id', 'location_id'])

        # Adding model 'Badge'
        db.create_table(u'userspace_badge', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=128)),
            ('name_af', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ar', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_az', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_bg', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_be', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_bn', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_br', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_bs', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ca', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_cs', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_cy', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_da', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_de', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_el', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_en', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_en_gb', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_eo', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_es', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_es_ar', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_es_mx', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_es_ni', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_es_ve', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_et', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_eu', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_fa', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_fi', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_fr', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_fy_nl', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ga', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_gl', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_he', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_hi', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_hr', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_hu', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ia', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_id', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_is', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_it', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ja', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ka', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_kk', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_km', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_kn', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ko', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_lb', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_lt', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_lv', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_mk', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ml', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_mn', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_my', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_nb', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ne', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_nl', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_nn', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_os', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_pa', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_pl', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_pt', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_pt_br', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ro', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ru', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_sk', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_sl', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_sq', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_sr', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_sr_latn', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_sv', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_sw', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ta', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_te', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_th', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_tr', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_tt', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_udm', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_uk', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_ur', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_vi', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_zh_cn', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('name_zh_tw', self.gf('django.db.models.fields.CharField')(max_length=128, null=True, blank=True)),
            ('description', self.gf('django.db.models.fields.TextField')()),
            ('description_af', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ar', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_az', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_bg', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_be', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_bn', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_br', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_bs', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ca', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_cs', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_cy', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_da', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_de', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_el', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_en', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_en_gb', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_eo', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_es', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_es_ar', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_es_mx', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_es_ni', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_es_ve', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_et', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_eu', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_fa', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_fi', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_fr', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_fy_nl', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ga', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_gl', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_he', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_hi', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_hr', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_hu', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ia', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_id', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_is', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_it', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ja', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ka', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_kk', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_km', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_kn', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ko', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_lb', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_lt', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_lv', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_mk', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ml', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_mn', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_my', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_nb', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ne', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_nl', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_nn', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_os', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_pa', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_pl', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_pt', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_pt_br', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ro', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ru', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_sk', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_sl', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_sq', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_sr', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_sr_latn', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_sv', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_sw', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ta', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_te', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_th', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_tr', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_tt', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_udm', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_uk', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_ur', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_vi', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_zh_cn', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('description_zh_tw', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('thumbnail', self.gf('django.db.models.fields.files.ImageField')(default='img/badges/badge.png', max_length=100)),
        ))
        db.send_create_signal(u'userspace', ['Badge'])

        # Adding M2M table for field user on 'Badge'
        m2m_table_name = db.shorten_name(u'userspace_badge_user')
        db.create_table(m2m_table_name, (
            ('id', models.AutoField(verbose_name='ID', primary_key=True, auto_created=True)),
            ('badge', models.ForeignKey(orm[u'userspace.badge'], null=False)),
            ('userprofile', models.ForeignKey(orm[u'userspace.userprofile'], null=False))
        ))
        db.create_unique(m2m_table_name, ['badge_id', 'userprofile_id'])

        # Adding model 'RegisterDemand'
        db.create_table(u'userspace_registerdemand', (
            ('activation_link', self.gf('django.db.models.fields.CharField')(max_length=1024)),
            ('ip_address', self.gf('django.db.models.fields.IPAddressField')(max_length=15)),
            ('email', self.gf('django.db.models.fields.EmailField')(max_length=256)),
            ('lang', self.gf('django.db.models.fields.CharField')(default='en', max_length=10)),
            ('date', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('user', self.gf('django.db.models.fields.related.ForeignKey')(related_name='registration', primary_key=True, to=orm['auth.User'])),
        ))
        db.send_create_signal(u'userspace', ['RegisterDemand'])

        # Adding model 'LoginData'
        db.create_table(u'userspace_logindata', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['auth.User'])),
            ('date', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('address', self.gf('django.db.models.fields.IPAddressField')(max_length=15)),
        ))
        db.send_create_signal(u'userspace', ['LoginData'])


    def backwards(self, orm):
        # Deleting model 'UserProfile'
        db.delete_table(u'userspace_userprofile')

        # Removing M2M table for field mod_areas on 'UserProfile'
        db.delete_table(db.shorten_name(u'userspace_userprofile_mod_areas'))

        # Deleting model 'Badge'
        db.delete_table(u'userspace_badge')

        # Removing M2M table for field user on 'Badge'
        db.delete_table(db.shorten_name(u'userspace_badge_user'))

        # Deleting model 'RegisterDemand'
        db.delete_table(u'userspace_registerdemand')

        # Deleting model 'LoginData'
        db.delete_table(u'userspace_logindata')


    models = {
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Group']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Permission']"}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'locations.location': {
            'Meta': {'object_name': 'Location'},
            'country_code': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'creator': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'created_locations'", 'blank': 'True', 'to': u"orm['auth.User']"}),
            'description': ('django.db.models.fields.TextField', [], {'max_length': '10000', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'image': ('django.db.models.fields.files.ImageField', [], {'default': "'img/locations/nowhere.jpg'", 'max_length': '100'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '64'}),
            'parent': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['locations.Location']", 'null': 'True', 'blank': 'True'}),
            'population': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '64'}),
            'users': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.User']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'userspace.badge': {
            'Meta': {'object_name': 'Badge'},
            'description': ('django.db.models.fields.TextField', [], {}),
            'description_af': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ar': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_az': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_be': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_bg': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_bn': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_br': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_bs': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ca': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_cs': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_cy': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_da': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_de': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_el': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_en': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_en_gb': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_eo': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_es': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_es_ar': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_es_mx': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_es_ni': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_es_ve': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_et': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_eu': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_fa': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_fi': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_fr': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_fy_nl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ga': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_gl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_he': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_hi': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_hr': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_hu': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ia': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_id': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_is': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_it': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ja': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ka': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_kk': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_km': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_kn': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ko': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_lb': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_lt': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_lv': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_mk': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ml': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_mn': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_my': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_nb': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ne': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_nl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_nn': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_os': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_pa': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_pl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_pt': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_pt_br': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ro': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ru': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_sk': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_sl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_sq': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_sr': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_sr_latn': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_sv': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_sw': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ta': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_te': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_th': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_tr': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_tt': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_udm': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_uk': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_ur': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_vi': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_zh_cn': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'description_zh_tw': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'name_af': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ar': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_az': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_be': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_bg': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_bn': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_br': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_bs': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ca': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_cs': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_cy': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_da': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_de': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_el': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_en': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_en_gb': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_eo': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_es': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_es_ar': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_es_mx': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_es_ni': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_es_ve': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_et': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_eu': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_fa': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_fi': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_fr': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_fy_nl': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ga': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_gl': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_he': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_hi': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_hr': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_hu': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ia': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_id': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_is': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_it': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ja': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ka': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_kk': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_km': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_kn': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ko': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_lb': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_lt': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_lv': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_mk': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ml': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_mn': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_my': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_nb': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ne': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_nl': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_nn': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_os': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_pa': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_pl': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_pt': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_pt_br': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ro': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ru': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_sk': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_sl': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_sq': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_sr': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_sr_latn': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_sv': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_sw': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ta': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_te': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_th': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_tr': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_tt': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_udm': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_uk': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_ur': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_vi': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_zh_cn': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'name_zh_tw': ('django.db.models.fields.CharField', [], {'max_length': '128', 'null': 'True', 'blank': 'True'}),
            'thumbnail': ('django.db.models.fields.files.ImageField', [], {'default': "'img/badges/badge.png'", 'max_length': '100'}),
            'user': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'badges'", 'blank': 'True', 'to': u"orm['userspace.UserProfile']"})
        },
        u'userspace.logindata': {
            'Meta': {'object_name': 'LoginData'},
            'address': ('django.db.models.fields.IPAddressField', [], {'max_length': '15'}),
            'date': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['auth.User']"})
        },
        u'userspace.registerdemand': {
            'Meta': {'object_name': 'RegisterDemand'},
            'activation_link': ('django.db.models.fields.CharField', [], {'max_length': '1024'}),
            'date': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '256'}),
            'ip_address': ('django.db.models.fields.IPAddressField', [], {'max_length': '15'}),
            'lang': ('django.db.models.fields.CharField', [], {'default': "'en'", 'max_length': '10'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'registration'", 'primary_key': 'True', 'to': u"orm['auth.User']"})
        },
        u'userspace.userprofile': {
            'Meta': {'object_name': 'UserProfile'},
            'avatar': ('django.db.models.fields.files.ImageField', [], {'default': "'img/avatars/anonymous.png'", 'max_length': '100'}),
            'background_image': ('django.db.models.fields.files.ImageField', [], {'default': "'img/backgrounds/background.jpg'", 'max_length': '100'}),
            'description': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'fb_url': ('django.db.models.fields.URLField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'gplus_url': ('django.db.models.fields.URLField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'lang': ('django.db.models.fields.CharField', [], {'default': "'en'", 'max_length': '10'}),
            'mod_areas': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'locations'", 'blank': 'True', 'to': u"orm['locations.Location']"}),
            'rank_pts': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'thumbnail': ('django.db.models.fields.files.ImageField', [], {'default': "'img/avatars/30x30_anonymous.png'", 'max_length': '100'}),
            'user': ('annoying.fields.AutoOneToOneField', [], {'related_name': "'profile'", 'unique': 'True', 'primary_key': 'True', 'to': u"orm['auth.User']"})
        }
    }

    complete_apps = ['userspace']